### ISSUE TITLE
[BUG]: Can't install with pipx

### ISSUE THREAD

**Issue by zsol** [wasi-master/fastero#4]
### Description of the bug

`pipx` doesn't find any binaries to run in `fastero`

### Steps To Reproduce

1. `pipx run fastero`
Output:
```
> pipx run fastero
fastero not found in package fastero. Available binaries:
```

**Comment by wasi-master** [comment]
Oh this is because of the pyproject.toml, I'll fix it in a bit

**Comment by wasi-master** [comment]
This should be fixed now :)
