### ISSUE TITLE
[BUG]: python_diff_between_two_lists_benchmark.sh has two slashes at end unlike other examples

### ISSUE THREAD

**Issue by fomightez** [wasi-master/fastero#5]
### Description of the bug

Open `python_diff_between_two_lists_benchmark.sh` and note it has `\\` as end of lines. That could doesn't work when I paste in a terminal. Whereas the other `.sh` files in example work.

### Steps To Reproduce

Open `python_diff_between_two_lists_benchmark.sh` and note it has `\\` as end of lines. The other `.sh` files just have single `\`.

**Comment by wasi-master** [comment]
I'll fix it tomorrow since it's nighttime here

**Comment by wasi-master** [comment]
Done
